### DISCUSSION TITLE
Docker Compose

### DISCUSSION THREAD

**Discussion by walchinsky** [PodcastGenerator/PodcastGenerator#664] [Ideas]
After looking into the work that [vonProteus](https://github.com/vonProteus/PodcastGenerator) has done with docker, I put together a simple docker-compose file.

docker-compose.yml
```
version: "3"
services:
  podcastgenerator:
    image: vonproteus/podcast-generator:latest
    ports:
      - "3045:80"
    volumes:
      - "./appdata:/app/PodcastGenerator/appdata"
    restart: "unless-stopped"
```
With the docker compose plugin installed
run
`docker compose up -d`
It would be great if docker can get a bit more exposure with Podcast Generator and have something like this added to the readme.
